### ISSUE TITLE
Misleading text on button on Ocean L2 Release web page

### ISSUE THREAD

**Issue by DrMaggie** [ICOS-Carbon-Portal/drupal#15]
On the web page (https://www.icos-cp.eu/data-products/ocean-release) describing the collection "ICOS release 2023-1 of Level 2 Ocean data", we provide a button up in the top right-hand corner with the text "View in the data portal". 

Taken in the context of the other release description information provided on the web page, it is natural to think that clicking the button will take the user over to the portal where a search for individual datasets included in the release will be performed, and the corresponding records shown. (In this particular case, 54 objects in total, from the 9 platforms/ships listed in the CO2 preview table further down on the collection release's web page.)

However, this is not the case; instead the user ends up with a list of all datasets that fulfil the more general criteria of being ICOS Level 2 Ocean data time series of the types 'ICOS OTC FOP Release' or 'ICOS OTC SOOP Release', (corresponding to the URL https://data.icos-cp.eu/portal/#%7B%22filterCategories%22%3A%7B%22project%22%3A%5B%22icos%22%5D%2C%22theme%22%3A%5B%22ocean%22%5D%2C%22level%22%3A%5B2%5D%7D%2C%22filterTemporal%22%3A%7B%22sf%22%3A%222020-05-31%22%7D%7D ), in this case returning 207 data objects from a much longer list of platforms/ships.

To minimise confusion, and be more aligned with realistic user expectations, my suggestion would be to change the text on the button to e.g. "Search for all Ocean Level 2 time series data", or similar.

**Comment by jonathanthiry** [comment]
I updated the data portal link to filter for data sampled and submitted in 2023, and this should give the correct list https://www.icos-cp.eu/data-products/ocean-release.
